# site name
prefixName: å¤¢ã¨ï¼¶ï¼²ã¨
siteName: ã“ã„ã—
# favicon and site master avatar
favicon: /images/favicon.png
avatar: /img/avatar.png
url: https://vivy.kgr514.com
description: ä½ å¥½ï¼è¿™é‡Œæ˜¯ç¥æ¥½ã“ã„ã—ï¼Œä¸€ä¸ªVRChatç©å®¶ï¼Œä¸€ä¸ªMtFï¼Œè¯·å¤šæŒ‡æ•™~
cdn: 
pjax: 1
# 1å¼€å¯
mathjax: 1

notice: 
lazyloadImg: https://jsd.onmicrosoft.cn/gh/imouup/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  ğŸ é¦–é¡µ: { path: / }
  ğŸ’¾å½’æ¡£: { path: /archives/ , submenus: {
    ğŸ¡ç”Ÿæ´»: {path: /categories/life/ },
    ğŸ“–å­¦ä¹ : {path: /categories/learn/ },
    ğŸ”§æŠ˜è…¾: {path: /categories/explore/ }
  }}
  ğŸ·ï¸æ ‡ç­¾: {path: /tags/ }
  ğŸ“¸å›¾é›†: {path: /tags/gallery/ }
  ğŸµç•™è¨€æ¿: { path: /comment/ }
  #å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
  ğŸ³ï¸â€âš§ï¸å…³Â·äº: { path: /about/ }
  


# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg:
  - /img/treasure1.png
  - /img/treasure2.png
  - /img/onimai1.png
  - /img/onimai2.png
# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: 

# startdash url, title, desc img
startdash:
  - {url: /life/hrt-records, title: HRT, desc: ä¸ªäººæ–¹æ¡ˆä¸æ•ˆæœ, img: /img/onimai1.png}
  - {url: https://space.bilibili.com/14842895, title: Bilibili, desc: åšä¸»çš„Bç«™é¦–é¡µ, img: /img/treasure1.png}
  - {url: https://twitter.com/KaguraKoishi, title: XXç©ºé—´ , desc: åšä¸»çš„æ¨ç‰¹å¤§å·, img: /img/treasure2.png}



# your site build time or founded date
siteBuildingTime: 12/17/2024

#social  url, img PCç«¯é…ç½®
social:
  æƒ³å’Œæˆ‘èŠå¤©?: {url: tencent://message/?uin=578183549, img: https://jsd.onmicrosoft.cn/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/qq.png}
  èµä¸¤ä¸ªç¡¬å¸å§w: {url: https://space.bilibili.com/14842895, img: https://jsd.onmicrosoft.cn/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/bilibili.png}
  ä¸€èµ·å¬æ­Œ!: {url: https://music.163.com/#/user/home?id=246884413, img: https://jsd.onmicrosoft.cn/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/wangyiyun.png}
  æ‰æ²¡æœ‰å¥½åº·çš„(: {url: https://twitter.com/KaguraKoishi, img: https://jsd.onmicrosoft.cn/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/twitter.png}
  ä½ æ˜¯è®¤çœŸçš„?: {url: mailto:KaguraKoishi@outlook.com, img: https://jsd.onmicrosoft.cn/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/email.svg}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: http://github.com/KaguraKoishi, fa: fa-github, color: 333}
  #weibo: {url: http://weibo.com/<username>?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=578183549&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

#donate:
  #paypal: https://www.paypal.me/<username>
  #alipay: https://jsd.onmicrosft.cn/gh/imouup/pico/picalipay.jpg
  #wechat: https://jsd.onmicrosft.cn/gh/imouup/pico/picwechatpay.jpg
  #wechatSQ: /img/custom/donate/


movies:
  url: #https://iamswlx-my.sharepoint.com/personal/mfuns_iamswlx_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=51300f43-a208-4ca9-b1ca-d4c53db97961&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvaWFtc3dseC1teS5zaGFyZXBvaW50LmNvbUAyYmE5YzYwOC1mMzEwLTRjOTItODNmOC1kMjY2MzZmMDY2MmYiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjQzMTA0NzQ1IiwiZXhwIjoiMTY0MzEwODM0NSIsImVuZHBvaW50dXJsIjoiMFBKU1NqZCthZnRac3hUa1NqODN3Vko2ZTZKMGcycE9vNUsrZ05oNFFHVT0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE2MCIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTWpaaU9EQm1ZekV0TjJWallTMDBaV0psTFdKa1pEUXRNelUxTUdVNFpHVXpNR05pIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik9XRTFaR1JrWWprdE9ESmhNaTAwTXpFMkxXRXpNMlV0TVdFeE1qVTJaV1V5TUdRMyIsImFwcF9kaXNwbGF5bmFtZSI6Im1tIiwiZmFtaWx5X25hbWUiOiJtZnVucyIsImFwcGlkIjoiZjkyMDkyZDItNjk3MC00Njg1LWFjMjQtNWRhZDI0YzNhNmJhIiwidGlkIjoiMmJhOWM2MDgtZjMxMC00YzkyLTgzZjgtZDI2NjM2ZjA2NjJmIiwidXBuIjoibWZ1bnNAaWFtc3dseC5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDE3NDFFNDA5MCIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAxNzQxZTQwOTBAbGl2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy53cml0ZSBhbGxzaXRlcy53cml0ZSIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjQwLjEyNi4yMy4zNiJ9.TjY2enJDOVlFTWxwdytkQ2w4eWdsclFTYmNlMXJJa0orMTJ2R2wxZTcyMD0&ApiVersion=2.0
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: #è¶…ç‡ƒç¥æ›²ã€ŠWakeã€‹è®©ä½ é‡æ‹¾äºŒæ¬¡å…ƒçš„ç¾å¥½
   
  

aplayer: 
  id: 307802458
  server: netease
  type: playlist
  fixed: true
  autoplay: true
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: false
v_appId: #iKXJinpG6tQvgt9RlQ9og31g-MdYXbMMI
v_appKey: #meMvgEKyT3cE0tLJGdSrSqrY

# Waline
waline:
  enable: false
  serverURL: #https://waline-46nj6p395-imouup.vercel.app/
  visitor: true #ç»Ÿè®¡é˜…è¯»é‡
  comment_count: true #ç»Ÿè®¡è¯„è®ºæ•°
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 20
  placeholder: æ¥å•Šï¼Œå¿«æ´»å•Šï¼ï¼ˆCtrl+Enterå‘é€ï¼‰ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #è®¾ç½®å¿…å¡«é¡¹
  background: #https://jsd.onmicrosft.cn/gh/imouup/pico/pic74841737 (1).gif #è¾“å…¥æ¡†æç¤ºåŠ¨ç”»
  
#ä¸è’œå­è®¡æ•°å™¨
busuanzi:
  switch: true

#æ¯æ—¥ä¸€è¨€
hitokoto: true

#å…¨ç«™ç°ç™½ä¸»é¢˜
gray: false


